CREATE TABLE orders
(
    id bigint generated by default as identity
    constraint order_pk primary key,
    order_number    varchar NOT NULL
);

CREATE TABLE order_line_items
(
    id bigint generated by default as identity
    constraint order_line_item_pk primary key,
    sku_code    varchar NOT NULL,
    price    decimal NOT NULL,
    quantity integer NOT NULL,
    order_id bigint,
    constraint orders_id_fk
       foreign key (order_id)
       references orders (id)
);