server:
  port: 8087

spring:
  application:
    name: inventory-service
  main:
    allow-bean-definition-overriding: true
  # Db properties
  datasource:
    url: jdbc:postgresql://localhost:5432/orders?socketTimeout=30
    username: order
    password: order
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: inventories

  # Kafka Properties
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      group-id: notificationId
      key-deserializer: 'org.apache.kafka.common.serialization.StringDeserializer'
      value-deserializer: 'org.springframework.kafka.support.serializer.JsonDeserializer'
      properties:
        spring:
          json:
            type:
              mapping: 'event:com.slozic.inventoryservice.event.OrderPlacedEvent'
            trusted:
              packages: '*'

  #RabbitMQ settings
  rabbitmq:
    host: localhost
    virtual-host: /
    username: guest
    password: guest

rabbitmq:
  exchange: order.exchange
  queue: order.queue
  routing-key: order.routing-key
  reply-timeout: 60000

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'